version:  '3.0'

services:
  main:
    container_name: main
    ports:
      - '5000:5000'
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    restart: always