version: '3.8'

services:
  serve:
    container_name: wildhunt-auth-service
    build:
      context: .
    env_file:
      - .env.local
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    command: nodemon src/api/v1/index.js
    restart: unless-stopped

  start:
    container_name: wildhunt-auth-service-prod
    build:
      context: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: node src/api/v1/index.js
    restart: unless-stopped